mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from .views import home1
from .views import Home
from .views import Base
from .views import Team
from videos.views import VideoListView
from videos.views import VideoDetailView
from videos.views import VideoCreateView, VideoUpdateView, VideoDeleteView
from .views import Landingpage, UserCreateView, UserCreateDoneView


# from videos.views import home
# from videos.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/done/$', UserCreateDoneView.as_view(), name='register_done'),
    #url(r'^$', home, name='home'),
    #url(r'^$', HomeView.as_view(), name='home'),          #r은 read 읽는 것 / ^$:아무것도 안들어 간것. ^:시작 / $:끝
    url(r'^$', Home.as_view()),
    url(r'^base/$', Base.as_view()),
    url(r'^team/$', Team.as_view()),
    # url(r'^about/$', about),
    # url(r'^team/$', team),
    url(r'^video/$', VideoListView.as_view(), name='video'),
    url(r'^video/(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video-detail'),
    url(r'^video/create/$', VideoCreateView.as_view(), name='video-create'),
    url(r'^video/(?P<pk>\d+)/update/$', VideoUpdateView.as_view(), name='video-update'),
    url(r'^video/(?P<pk>\d+)/delete/$', VideoDeleteView.as_view(), name='video-delete'),
    url(r'^index/$', Landingpage.as_view()),
    url(r'^photo/', include("photo.urls", namespace='photo'))
]

photo/urls.py
from django.conf import settings
from django.conf.urls.static import url, static

from .views import (
    PhotoListView,
    PhotoDetailView,
)

urlpatterns =[
    url(r'^$', PhotoListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', PhotoDetailView.as_view(), name='detail'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from .fields import ThumbnailImageField

# Create your models here.

class Photo(models.Model):
    title = models.CharField(max_length=120)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('photo Description', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:detail', args=(self.id,))

videos/models.py
from django.db import models

# Create your models here.
class Video(models.Model):
    title = models.CharField(max_length=120)
    embed_code = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return '/video/'

photo/forms.py
from django import forms

from .models import Photo

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['title', 'image', 'description']

videos/forms.py
from django import forms

from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'embed_code']

mysite/views.py
from django.http import HttpResponse
from django.views.generic import View       # generic:
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.forms import UserCreationForm        #form만드는 것 비디오 폼할 때도 넣었다.
from django.core.urlresolvers import reverse_lazy

#def home1(request):
#    text = "Hello World"
#    return HttpResponse(text)
#def about(request):
#    text ="<h1>우리에 대한 소개</h1>"
#    text +="좋은 회사입니다."
#    return HttpResponse(text)
#def team(request):
#    text = "<h1>팀장 : John</h1>"
#    text +="<h1>팀원 : Jane</h1>"
#    return HttpResponse(text)

class Home(View):
    def get(self, request, *args, **kwargs):
        return render(request, "home.html", {})

class Base(View):
    def get(self, request, *args, **kwargs):
        return render(request, "base.html", {})

class Team(View):
    def get(self, request, *args, **kwargs):
        context = {
            "team" : "숭이",
            "number" : "10명",
        }
        return render(request, "team.html", context)

        # 함수 get방식을 쓰는 것
        # request의 텍스트 불러오기 {} : 서버에서 표시하고 싶은 값이 있을 때 쓰는 것
        # 클래스는 대문자, 함수는 소문자.

class Landingpage(View):
    def get(self, request, *args, **kwargs):
        return render(request, "landingpage.html", {})

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneView(TemplateView):
    template_name = 'registration/register_done.html'

photo/views.py
from django.shortcuts import render

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Photo
from .forms import PhotoForm

# Create your views here.

class PhotoListView(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

class PhotoDetailView(DeleteView):
    model = Photo
    template_name = 'photo/photo_detail.html'

class PhotoCreateView(CreateView):
    model = Photo
    template_name = 'photo/photo_create.html'
    form_class = PhotoForm

videos/views.py
from django.shortcuts import render

# Create your views here.
from .models import Video
from django.views.generic import ListView
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from .forms import VideoForm


class VideoListView(ListView):
    queryset = Video.objects.all()
    # all_count = Video.objects.all().count()
    #print(queryset)
    def get_context_data(self, *args, **kwargs):
        context = super(VideoListView, self).get_context_data(*args, **kwargs)   #super:부모?
        # context['count'] = 4
        context['all_count'] = Video.objects.all().count()
        return context

class VideoDetailView(DetailView):
    queryset = Video.objects.all()          #video의 모든 걸 가져온다는 의미

    def get_context_data(self, *arg, **kwargs):
        context = super(VideoDetailView, self).get_context_data(*arg, **kwargs)
        return context

class VideoCreateView(CreateView):
    model = Video
    form_class = VideoForm
    success_url = '/video/'

    def form_valid(self, form):
        # print('form_valid')
        # print(self.request.POST.get('title'))
        # print(self.request.POST.get('embed_code'))
        return super(VideoCreateView, self).form_valid(form)

    def form_invalid(self, form):
        # print('form_in_valid')
        # print(self.request.POST.get('title'))
        # print(self.request.POST.get('embed_code'))
        return super(VideoCreateView, self).form_invalid(form)

class VideoUpdateView(UpdateView):
    model = Video
    form_class = VideoForm

class VideoDeleteView(DeleteView):
    queryset = Video.objects.all()
    success_url = '/video/'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>{% block title %}Base{% endblock %}</title>

<!-- google web font -->
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">

<!--bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">


</head>

<body>


<div class="container">
{% block login %}
    <div class="row">
        <div class="col-12 text-right">
            {% if user.is_active %}
                <a href="{% url 'logout' %}">로그아웃</a>
                <a href="{% url 'password_change' %}">패스워드 변경</a>
            {% else %}
                <a href="{% url 'login' %}">로그인</a>
                <a href="{% url 'register' %}">회원가입</a>
            {% endif %}
        </div>
    </div>
{% endblock %}
    <div class="row">
        <div class="col-md-2">
            {% block sidebar %}
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'video' %}">Video</a></li>
                <li><a href="/index/">Landing Page</a></li>
                <li><a href="/photo/">Photo</a></li>
            </ul>
            {% endblock %}
        </div>
        <div class="col-md-10">
            {% block content %}
            <h1>base.html 입니다.</h1>
            {% endblock content %}
        </div>
    </div>
</div>



<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- bootstrap javascript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" ></script>
</body>
</html>

templates/defaults/head.html
    {% load static %}

    <!--google web font-->
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light+Two" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=ABeeZee" rel="stylesheet">

    <!--font awesome-->
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">

    <!-- favicon 아이콘 불러오기 -->
    <link rel="shortcut icon" href="{% static 'image/img/favicon.ico' %}">

    <!--Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <!--animate css-->
    <link rel="stylesheet" href="{% static 'css/animate/animate.css' %}">

    <!--magnific-popup-->
    <link rel="stylesheet" href="{% static 'css/magnific-popup/magnific-popup.css' %}">

    <!--our-carousel-->
    <link rel="stylesheet" href="{% static 'css/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl-carousel/owl.theme.default.css' %}">

    <!-- style.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

templates/defaults/scripts.html
{% load static %}

<!--jQuery-->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
<!--Bootstrap-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

<!--wow.min.js-->
<script src="{% static 'js/wow/wow.min.js' %}"></script>

<!--magnific-popup-->
<script src="{% static 'js/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

<!--our-carousel-->
<script src="{% static 'js/owl-carousel/owl.carousel.min.js' %}"></script>

<!--jquery watpoints-->
<script src="{% static 'js/counter/jquery.waypoints.min.js' %}"></script>

<!--jquery counterup-->
<script src="{% static 'js/counter/jquery.counterup.min.js' %}"></script>

<!--custom.js-->
<script src="{% static 'js/custom.js' %}"></script>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}

<h1>Welcome to Home</h1>
<h3>안녕하세요 </h3>
<img src="{% static 'image/img/work/1.jpg' %}">


{% endblock %}

templates/index.html
{% load static %}

<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">      <!--가장 최근 브라우저를 불러오는 것-->
    <meta name="viewport" content="width=device-width, initial-scale=1">  <!--가로길이를 디바이스에 맞추는 것(반응형웹)-->
    <title>{% block title %} Modern Responsible Website {% endblock %}</title>

    {% include 'defaults/head.html' %}

</head>

<body>
<!--menu-->
    <header>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
            <a class="navbar-brand" href="#"><img src="{% static 'image/img/logo.png' %}"></a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarTogglerDemo02"
                    aria-controls="navbarTogglerDemo02"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <!--navbarTogglerDemo02 : lg사이즈에서 메뉴 내리는 것 명령하는 id-->
                <ul class="navbar-nav">
                    <li class="nav-item active"><a class="nav-link" href="#">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#work">Work</a></li>
                    <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>
                    <li class="nav-item"><a class="nav-link" href="#testimonial">Customer</a></li>
                    <li class="nav-item"><a class="nav-link" href="#pricing">Price</a></li>
                    <li class="nav-item"><a class="nav-link" href="#stats">Stats</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    <li class="nav-item"><a class="nav-link" href="/video/">Videos</a></li>
                </ul>
            </div>
        </nav>
    </header>
{% block content %}

{% endblock content %}
{% include 'defaults/scripts.html' %}
</body>
</html>

templates/photo/photo_create.html
{% extends "base.html" %}

templates/photo/photo_detail.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form>
              <div class="form-group row">
                <label for="inputEmail3" class="col-sm-3 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="email" class="form-control" id="inputEmail3" value="{{ object.title }}" disabled>
                </div>
              </div>

              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-3 col-form-label">Image</label>
                <div class="col-sm-8">
                  <img class="img-fluid" src="{{ object.image.url }}">
                </div>
              </div>

                <div class="form-group row">
                <label for="inputPassword3" class="col-sm-3 col-form-label">Descriptions</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" disabled>{{object.description}}</textarea>
                </div>
              </div>

              <div class="form-group row">
                <div class="col-sm-11 text-right">
                  <button type="submit" class="btn btn-primary">Update</button>
                  <a href="{% url 'photo:list' %}" class="btn btn-secondary" role="button">Photo</a>
                </div>
              </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/photo/photo_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Image</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{{item.get_absolute_url}}">{{ item.title }}</a></td>
                        <td><img class="img-fluid img-thumbnail" src="{{ item.image.thumb_url }}"></td>
                        <td>{{ item.timestamp|date:"Y-m-d" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>Title</title>-->
<!--</head>-->
<!--<body>-->
<!--{% for item in object_list %}-->
    <!--{{ item.title }}-->
    <!--<img src="{{ item.image.thumb_url }}">-->
    <!--{{ item.timestamp }}-->
    <!--<br>-->
<!--{% endfor %}-->
<!--</body>-->
<!--</html>-->

templates/team.html
{% extends "base.html" %}

{% block sidebar %}
    <ul>
        <li><a href="/">HOME</a></li>
        <li><a href="/team/">팀명</a></li>
        <li>팀원</li>
    </ul>
{% endblock %}

{% block content %}
<h1>팀은 우수한 팀입니다.</h1>
{% endblock %}

templates/videos/video_confirm_delete.html
{% extends "base.html" %}
    {% block content %}
    <br><br>
    <form method="post" action="">
        {% csrf_token %}
        <p class="h2">정말 삭제하겠습니까?</p>
        <button type="submit" class="btn btn-primary" role="button">OK</button>
        <a href="{% url 'video-detail' object.id %}" class="btn btn-secondary">Back</a>
    </form>
{% endblock %}

templates/videos/video_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h3>{{object.title}}</h3>
            <br>
            <p>{{object.embed_code|safe}}</p>
            <br>
            <a href="{% url 'video-update' object.id %}" class="btn btn-primary" role="button">Update</a>
            <a href="{% url 'video-delete' object.id %}" class="btn btn-danger" role="button">Delete</a>
            <a href="javascript:history.back()" class="btn btn-secondary" role="button">Back</a>
        </div>
    </div>
</div>
{% endblock %}

templates/videos/video_form.html
{% extends "base.html" %}
    {% block content %}
    <br>
    <form method="post" action="">{% csrf_token %}
      <div class="form-group row">
        <label for="id_title" class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-8">
          <input type="text" class="form-control" id="id_title" name="title" placeholder="타이틀을 입력하세요">
        </div>
      </div>
      <div class="form-group row">
        <label for="id_embed_code" class="col-sm-2 col-form-label">Embed code: </label>
        <div class="col-sm-8">
            <textarea cols="40" class="form-control" id="id_embed_code" name="embed_code" rows="10" placeholder="코드를 입력하세요" required></textarea>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-10 text-right">
            <input type="submit" value="Send" class="btn btn-primary">
            <a href="javascript:history.back()" class="btn btn-secondary" role="button">Back</a>
        </div>
      </div>
    </form>
    <!--<form method="post" action="">-->
        <!--{% csrf_token %}            &lt;!&ndash;폼태그 앞에는 해킹을 막기위한 {% csrf_token %} 넣어야 한다&ndash;&gt;-->
        <!--{{form.as_p}}-->
        <!--<hr>-->

        <!--<p>-->
             <!--<label for="id_title">Title:</label>-->
             <!--<input id="id_title" maxlength="120" name="title" type="text" required />-->
            <!--&lt;!&ndash;name이 form.py의 키 벨류값으로 들어온다&ndash;&gt;-->
        <!--</p>-->
        <!--<p>-->
             <!--<label for="id_embed_code">Embed code:</label>-->
             <!--<textarea cols="40" id="id_embed_code" name="embed_code" rows="10" required></textarea>-->
        <!--</p>-->
        <!--<input type="submit" value="Send" class="btn btn-primary">-->
        <!--<a href="javascript:history.back()" class="btn btn-secondary" role="button">Back</a>-->
    <!--</form>-->
    {% endblock %}

templates/videos/video_list.html
{% extends "base.html" %}


{% block content %}
<br>
<a href="{% url 'video-create' %}" class="btn btn-primary" role="button">Video-Create</a>
<br><br>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <!--<th scope="col" class="text-center">비디오 1</th>-->
      <!--<th scope="col" class="text-center">비디오 2</th>-->
      <!--<th scope="col" class="text-center">비디오 3</th>-->
      <th colspan="3" scope="col" class="text-center">
          총 비디오 {{all_count}}
      </th>
    </tr>
  </thead>
  <tbody>
        <!--<tr>-->
    {% for object in object_list %}

        <tr>
          <td><a href="{% url 'video-detail' object.id %}">
              <!--<a href="/video/{{object.id}}/">-->
              <!--{{object.embed_code|safe}} <br>-->
              <!--<center><b>{{object.title}}</b></center>-->
              {{ object.title }}
              </a>
          </td>
          <td>{{ object.timestamp|date:"Y-m-d [H:i:s]" }}</td>
          <td><a href="{% url 'video-update' object.id %}" class="btn btn-success" role="button">Update</a></td>
        <!--{% if forloop.counter|divisibleby:2 %}-->
        </tr>
            <!--{% if forloop.counter != all_count %} <tr>{% endif %}-->
        <!--{% endif %}-->

        <!--</tr>-->
    {% endfor %}
  </tbody>
</table>

{% endblock %}